#!/bin/bash
set -e
set -o pipefail
shopt -sq nullglob

# Configuration
# ------------------------------------------------------------------------------
DIR="/www/software-engineering"
HOST=www.eul.ink
LOGIN=boisgera

txt_file() {
  txt_files=(*.txt)
  local len=${#txt_files[@]}
  if [ $len = 0 ]; then
    echo "error: no txt file found"
    exit 1
  elif [ $len -gt 1 ]; then
    echo "error: several txt files found"
    exit 1
  else
    echo "${txt_files[0]}"
  fi
}

txt=$(txt_file)
doc="${txt%.*}"

# Helpers
# ------------------------------------------------------------------------------
escape() {
  echo $(printf %q "$1")
}


# Convention over Configuration
# ------------------------------------------------------------------------------
txt=$(ls *.txt)
doc="${txt%.*}"
host="$LOGIN@$HOST"
target="${DIR}"

# Nota: rsync does not create intermediate directory,
#       but it will happily create them if the directory
#       itself is scheduled for transfer...
# OK, use recursive mode (just need to create the top-level target)



# Gather Files
# ------------------------------------------------------------------------------

# Documents and Archive
exts=(txt json html pdf zip)
files=()
for ext in "${exts[@]}"
do
  files+=("$doc.$ext")
done

# Images
if [ -e images ]; then
  files+=("images")
fi

# Bibliography
if [ -e bibliography ]; then
  files+=("bibliography")
fi

# Add docs
if [ -e documents ]; then
  files+=("documents")
fi


# Ship & Tweak
# ------------------------------------------------------------------------------

# Ship
ssh $host mkdir -p "$target"
rsync -aRv "${files[@]}" "$host:$target"

# Make index.html
ssh "$host" rm -rf "$target/index.html"
ssh "$host" ln -s "$target"/$(escape "$doc").html "$target/index.html"
